### ISSUE TITLE
help command

### ISSUE THREAD

**Issue by cureseven** [shiiyan/my-sukkirisu-bot#29]
I want help command
ex

request
```
@Sukkirisu Bot help
```

responce
```
メンションして以下を含めた投稿を行ってください
スッキリす：今日のすっきりすランキングを全て表示
個人スッキリす：ユーザとその誕生月を設定した場合、登録されているユーザのランキングを表示
{ユーザー}は{誕生月}月生まれ：ユーザに対して誕生月を設定する

0分~30分、31~59分の30分単位で再度リクエストを送ることができるようになります
```

**Comment by shiiyan** [comment]
Good idea.
I implemented this feature in here. [ec8dd21](https://github.com/shiiyan/my-sukkirisu-bot/commit/ec8dd21d0362d4df36b316507be51b15b4885152)

**Comment by cureseven** [comment]
Thanks for solving!
